config/routes.rb
TAShare::Application.routes.draw do
  devise_for :users

  root 'home#homepage'
  resources :home do
    collection do
      get 'homepage'
      get 'help'
      get 'setting'
    end
  end

  resources :class_ta do
    collection do
      get 'resourcejs'
      get 'addlike'
      get 'addbookmark'
      get 'removelike'
      get 'removebookmark'
      get 'removeresource'
      post 'addprofilepic'
      get 'addenroll'
      post 'createClass'
    end
  end

  resources :resources
  resources :audios, :controller => "resources", :type => "Audio"
  resources :notes, :controller => "resources", :type => "Note"
  resources :problems, :controller => "resources", :type => "Problem"
  resources :videos, :controller => "resources", :type => "Video"
  resources :websites, :controller => "resources", :type => "Website"

  

end

app/models/audio.rb
class Audio < Resource
	 include ClassTaHelper

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user
	belongs_to :video
	belongs_to :website
	belongs_to :audio
	belongs_to :note
	belongs_to :problem
end

app/models/class_ta.rb
class ClassTa < ActiveRecord::Base
	has_many :enrollments
	has_many :users, through: :enrollments
	has_many :videos
	has_many :websites
	has_many :audios
	has_many :notes
	has_many :problems
	has_many :vieweds
	has_many :resources
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :user
	belongs_to :class_ta
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
  belongs_to :website
  belongs_to :audio
  belongs_to :note
  belongs_to :problem
  # type id "Video", "Website", "Audio", "Note", "Problem"

end

app/models/note.rb
class Note < Resource
	include ClassTaHelper

end

app/models/problem.rb
class Problem < Resource
	include ClassTaHelper

end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :class_ta
	belongs_to :user
	belongs_to :like
	belongs_to :bookmark
	has_many :likes
	has_many :bookmarks
	has_attached_file :file, 
        :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
        :default_url => "/images/:style/missing.png"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  has_many :enrollments
  has_many :class_tas, through: :enrollments
  has_many :resources
  has_many :likes
  has_many :bookmarks
  has_many :vieweds
end

app/models/video.rb
class Video < Resource
	include ClassTaHelper

end

app/models/viewed.rb
class Viewed < ActiveRecord::Base
	belongs_to :user
	belongs_to :class_ta
end

app/models/website.rb
class Website < Resource
	include ClassTaHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
  def classjson
    @class_list = []
    ClassTa.all.each do |classTT|
      obj = {:name => classTT.name.to_s, :number => classTT.number.to_s, :id => classTT.id, :link  => url_for(:controller => "/class_ta", :action => "show", :id => classTT.id).to_s}
      @class_list.push(obj)
    end
    @class_list
  end
end

app/helpers/class_ta_helper.rb
module ClassTaHelper
  def as_json(options={})
    super(options.merge(:include => [:type, :likes, :bookmarks]))
  end

  def type
    r  = self.attributes["type"]
    def r.serializable_hash(arg)
      self
    end
    r
  end
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="TAShareApp">
<head>
    <title>TAShare</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!-- // <script type="text/javascript" src="./app/assets/javascript/navbar.js"></script> -->

</head>

<body style = "font-family: GandhiSans;">
  <script>
    var class_list = <%= raw(classjson().to_json)%>;
    initNavBar();
  </script>

  <!-- <div id = "divPusher"></div> -->

  <!-- <div class="center">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div> -->
  <% if current_user != nil%>
  <div id="navbar" ng-controller = "NavbarCtrl">
    <div id = 'navContainer'>
      <div id = 'navLeft'>
        <div id='logo'>        
          <h1 style = 'margin-top: 1px; padding: 5px; font-family: BebasNeueBold; background-color: white; border: 0; border-radius: 5px;'>
          <%= link_to "TA-Share", root_path %>
        </h1>
      </div>
        <input type = 'text' id = 'search' placeholder = 'Search for Classes'>
        <span class="glyphicon glyphicon-search" style = "margin-left: -36px; color: black"></span>
        <!-- <select id = "search" style = "border: 0;
      border-radius: 5px;
      margin-top: 5px;
      margin-left: 20px;
      padding: 10px;
      font-size: 14pt;
      min-width: 150px;
      max-width: 500px;
      color: black;
      height: 40px;">
          <option ng-repeat = "class in classes" ng-click = "goToPage(class.link)">{{class.number}}: {{class.name}}</option>
        </select> -->
        <div style="display:inline-block;" id="addClassContainer">
          <span class="glyphicon glyphicon-plus-sign" id="addClass" data-toggle="modal" data-target="#addClassModal" style="cursor: pointer; margin-left: 20px; margin-top: -3px;" title="Create Class"></span>
        </div>
      </div>

      <div id = 'navRight'>
        <div style = "position: relative; width: 45px; height: 45px; cursor: pointer; display: inline-block" data-toggle="modal" data-target="#picModal">
          <%= image_tag @current_user.avatar? ? @current_user.avatar.url(:thumb) : "profPic.png", {id: 'profPic', class: 'img-circle', style: 'position: absolute; height: 100%;'} %>
          <div id = "profImgOverlay" title = "Edit Profile Picture" data-placement = "bottom" data-toggle = "tooltip"><span class = "glyphicon glyphicon-edit" style = "margin-top: 13px; margin-left: 14px; font-size: 18px"></span></div>
        </div>
        <div id = 'name'> <%= @current_user.first_name %></div>

        <div class = "dropdown" style="display: inline-block;" id="gear" >
            <span id = "logOut" class = "glyphicon glyphicon-log-out" data-toggle="dropdown"></span>
            <ul class="dropdown-menu pull-right" role="menu" > 
              <li id = "signOut" role="presentation">
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="picModal"  role="dialog" aria-labelledby="picModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h1 class="modal-title" id="picModalLabel">Edit Profile Picture</h1>
        </div>
      <div class="modal-body">
        <%= form_tag(addprofilepic_class_ta_path,method: "post", :multipart => true) do |f| %>
            <div class="form-group">
              <!-- <%= label_tag :avatar %> -->
              <%= file_field_tag :avatar, :required=>:true, :class => 'upload-image' %></div>
              <div>
            </div>         
            <div class="modal-footer">
              <%= submit_tag nil, :class=> "btn btn-primary btn-large" %>
            </div>
            <% end %>
      
      </div>
      </div>
    </div>
  </div>

    <div class="modal fade" id="addClassModal"  role="dialog" aria-labelledby="addClassLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h1 class="modal-title" id="addClassLabel">Create Class</h1>
        </div>
      <div class="modal-body">
        <%= form_tag(createClass_class_ta_path,method: "post", :class => "add-class") do |f| %>
            <div class="form-group">
              <%= text_field_tag :number, nil, :placeholder => "Class Number"%>
            </div>
            <div class="form-group">
              <input id="nameT" name="name" placeholder="Class Name" type="text">
            </div>
            <div class="form-group">
              <%= text_area_tag :description, nil, :placeholder => "Class Description"%>
            </div>

            <div class="modal-footer">
              <%= submit_tag nil, :class=> "btn btn-primary btn-large" %>
            </div>
            <% end %>
      </div>
      </div>
    </div>
  </div>


  <div class="modal fade" id="addEnrollment"  role="dialog" aria-labelledby="addEnrollmentLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h1 class="modal-title" id="picModalLabel">Add to Your My Classes</h1>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label id = "addEnroll-label" for="addEnroll-class">Class:</label>
            <input id = "addEnroll-class" name = "addEnroll-class" type = "text" placeholder="Select Class to add here!"> 
          </div>
        </div>        
<!--         <div class="modal-footer">
          <button type = "button" data-dismiss="modal" id = "addEnroll-button" class = "btn btn-primary btn-large" >Add Class</button>
        </div> -->
      </div>
    </div>
  </div>

  <%end%>

  <div ng-view>
    <%= yield %>
  </div>


</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>